### ISSUE TITLE
php_test_client not working correctly with OAuth

### ISSUE THREAD

**Issue by raumaankidwai** [Khan/khan-api#91] opened 2015-08-01 11:50 UTC
The examples/php_test_client client isn't working properly. When I try to use it it gives an error on top of another error. The log in is successful but when I try to GET /api/v1/user I get this error:

Fatal error: Uncaught exception 'OAuthException2' with message 'Request failed with code 401: OAuth error. Invalid access token: ' in /Library/WebServer/Documents/private/php_test_client/oauth-php/library/OAuthRequester.php:117 Stack trace: #0 /Library/WebServer/Documents/private/php_test_client/ka_client.php(95): OAuthRequester->doRequest(0) #1 {main} thrown in /Library/WebServer/Documents/private/php_test_client/oauth-php/library/OAuthRequester.php on line 117

If I comment out line 117 of php_test_client/oauth-php/library/OAuthRequester.php, I get this error:

OAuth error. Invalid access token:

It seems like the access token is not being sent. I'm not experienced with OAuth however so I don't know how to fix this...

**Comment by alangpierce** [comment] 2015-09-20 01:36
Sorry for the delay in responding to this. I just tried the PHP client and it seems to be working just fine for me, so I'm not sure what the problem might be. My best guess is that it has to do with Session storage in the oauth-php library, but I unfortunately don't have much experience with that library or PHP in general. If you track down the solution or a reliable way to reproduce the issue, it would be good to get more that information, but I'm closing this issue in the meantime since I can't reproduce the problem.

**Closed by alangpierce** 2015-09-20 01:36 UTC
